/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

package com.huawei.hms.urbanhomeservices.kotlin.clouddb;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

/**
 * Definition of ObjectType LoginInfo.
 *
 * @author : Huawei
 * @since : 2021-02-08
 */

@PrimaryKeys({"user_email"})
public class LoginInfo extends CloudDBZoneObject {
    private Integer user_id;
    private String user_email;
    private String user_name;
    private String user_phone;
    private String photo_uri;
    private String device_token;

    @DefaultValue(booleanValue = true)
    private Boolean shadow_flag;

    public LoginInfo() {
        super(LoginInfo.class);
        this.shadow_flag = true;
    }

    public void setUserId(Integer user_id) {
        this.user_id = user_id;
    }

    public Integer getUserId() {
        return user_id;
    }

    public void setUserEmail(String user_email) {
        this.user_email = user_email;
    }

    public String getUserEmail() {
        return user_email;
    }

    public void setUserName(String user_name) {
        this.user_name = user_name;
    }

    public String getUserName() {
        return user_name;
    }

    public void setUserPhone(String user_phone) {
        this.user_phone = user_phone;
    }

    public String getUserPhone() {
        return user_phone;
    }

    public void setPhotoUri(String photo_uri) {
        this.photo_uri = photo_uri;
    }

    public String getPhotoUri() {
        return photo_uri;
    }

    public void setDeviceToken(String device_token) {
        this.device_token = device_token;
    }

    public String getDeviceToken() {
        return device_token;
    }

    public void setShadowFlag(Boolean shadow_flag) {
        this.shadow_flag = shadow_flag;
    }

    public Boolean getShadowFlag() {
        return shadow_flag;
    }

}
