/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.hms.quickline.data.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;


/**
 * Definition of ObjectType CallsSdp.
 *
 * @since 2022-07-05
 */
@PrimaryKeys({"meetingID"})
public final class CallsSdp extends CloudDBZoneObject {
    private String meetingID;

    private Text sdp;

    private String callType;

    public CallsSdp() {
        super(CallsSdp.class);
    }

    public void setMeetingID(String meetingID) {
        this.meetingID = meetingID;
    }

    public String getMeetingID() {
        return meetingID;
    }

    public void setSdp(Text sdp) {
        this.sdp = sdp;
    }

    public Text getSdp() {
        return sdp;
    }

    public void setCallType(String callType) {
        this.callType = callType;
    }

    public String getCallType() {
        return callType;
    }

}