/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import <AGConnectDatabase/AGConnectDatabase.h>

NS_ASSUME_NONNULL_BEGIN

@interface user3 : AGCCloudDBObject
@property (nonatomic, strong) NSNumber<AGCLong> *id;
@property (nonatomic, copy) NSString *fullname;
@property (nonatomic, copy) NSString *username;
@property (nonatomic, copy) NSString *email;
@end

NS_ASSUME_NONNULL_END