/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import "user3.h"

@implementation user3

+ (NSArray<NSString *> *)primaryKeyProperties {
    return @[@"id"];
}

+ (NSDictionary<NSString *, NSArray *> *)indexProperties { 
    return @{@"id" : @[@"id"]};
}

+ (NSArray<NSString *> *)notNullProperties {
    return @[@"id"];
}

@end
