/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.hms.couriertracking.data.network.model;

import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;

/**
 * Definition of ObjectType Order.
 *
 * @since 2022-09-15
 */
@PrimaryKeys({"id"})
@Indexes({"productTitle:productTitle", "storeLat:storeLat", "productPhotoUrl:productPhotoUrl", "id:id", "storeLng:storeLng", "productPrice:productPrice", "productDescription:productDescription", "status:status"})
public final class Order extends CloudDBZoneObject {
    private String id;

    private String productTitle;

    private String productDescription;

    private String productPhotoUrl;

    private Double productPrice;

    private Integer status;

    private Double storeLat;

    private Double storeLng;

    public Order() {
        super(Order.class);
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setProductTitle(String productTitle) {
        this.productTitle = productTitle;
    }

    public String getProductTitle() {
        return productTitle;
    }

    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    public String getProductDescription() {
        return productDescription;
    }

    public void setProductPhotoUrl(String productPhotoUrl) {
        this.productPhotoUrl = productPhotoUrl;
    }

    public String getProductPhotoUrl() {
        return productPhotoUrl;
    }

    public void setProductPrice(Double productPrice) {
        this.productPrice = productPrice;
    }

    public Double getProductPrice() {
        return productPrice;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStoreLat(Double storeLat) {
        this.storeLat = storeLat;
    }

    public Double getStoreLat() {
        return storeLat;
    }

    public void setStoreLng(Double storeLng) {
        this.storeLng = storeLng;
    }

    public Double getStoreLng() {
        return storeLng;
    }

}
